### ISSUE TITLE
Jaggy, while fps are changing

### ISSUE THREAD

**Issue by FluffyDiscord** [masagrator/Xenoblade2DynFPS#2]
This mod creates really smooth 60fps experience, but only when its exactly 60fps. Any framerate drops bellow this number make the game unfortunately unplayable. The framepacing goes out of the window and I can see something I can describe only as "two frames going forward, and one jumping back" - the camera is much worse.

Unfortunately the simple 60fps hack seems to be smoother in that regards, even tho it slows down the gameplay.

Is there something I can do on my end? using 5800x3d and rtx 4090

**Comment by masagrator** [comment]
```
exlaunch plugin for Xenoblade Chronicles 2 that is taking naive approach at adjusting game speed dynamically.
```
naive is the key part here. You cannot expect from such simple plugin to solve something devs couldn't do for years. Game speed dynamic adjustments require proper rendering pipeline changes. 

```
Known issues that probably will never be fixed:

Game has big issues with fluid asset streaming, so it can affect stability of speed calculation at higher framerates (> 50 FPS)
```

It was already mentioned. And this is mainly targeting Switch hardware. There is a big difference in how frames are rendered in emus and Switch hardware, so expected timings will definitely vary. If emulator Can't hold stable 60 FPS on such machine, I advise to get in touch with emu developers to do something about it as you should definitely hold stable 60 FPS through whole game with such hardware. Except for shader recompilation stutter moments which you can do nothing about. 

On Switch FPS can drop to 40 even with high handheld clocks without charger plugged, so this is still a better solution for those people than 33% slowdown.
