### ISSUE TITLE
How to modify it to dynamic 30 fps?

### ISSUE THREAD

**Issue by jsyumg** [masagrator/Xenoblade2DynFPS#7]
Ive been playing the game as normal with the 60 fps, however my steam deck cant handle it and playing without any mods makes the speed of the game tied to the fps, therefore i was wondering if there was a way to turn this into a dynamic 30 fps mod so if it goes below 30, the speed remains the same

**Comment by masagrator** [comment]
Just install this mod and use emulator to lock to 30 FPS. How Idk, I don't use emulators. I remember only something about setting game speed in yuzu settings.
