### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by EmmanueldelaCruz** [masagrator/Xenoblade2DynFPS#8]
I have a basic laptop but this mod works great in Ryujinx. In Yuzu it’s slow. The thing it’s that during a chain attack it freezes. And also in the main manu it freezes and I have to restart the game. This is when the mod it’s activated.

**Comment by masagrator** [comment]
If it's not working specifically with yuzu, ask their devs to fix... Ah right, yuzu is dead. I don't recognize any fork of it if it's using the same name as it means total mess.

**Comment by EmmanueldelaCruz** [comment]
Ah… ok. Thank you, anyway.
